//
// Generated file, do not edit! Created by opp_msgc 4.2 from ClusterMCFA/ClusterMCFAPkt.msg.
//

#ifndef _CLUSTERMCFAPKT_M_H_
#define _CLUSTERMCFAPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ClusterPkt_m.h"
// }}



/**
 * Enum generated from <tt>ClusterMCFA/ClusterMCFAPkt.msg</tt> by opp_msgc.
 * <pre>
 * enum MCFAMessageTypes 
 * { 
 *     	MCFA_ASFREQ 	= 15010;
 *     	MCFA_ASFREP		= 15020;
 *     	MCFA_RERM 		= 15030;
 *     	MCFA_JREQ 		= 15040;
 *     	MCFA_JREP 		= 15050;
 *     	MCFA_CHSEL	 	= 15060;
 *     	MCFA_LREQ 		= 15070;
 *     	MCFA_MOBINFO	= 15080;
 * };
 * </pre>
 */
enum MCFAMessageTypes {
    MCFA_ASFREQ = 15010,
    MCFA_ASFREP = 15020,
    MCFA_RERM = 15030,
    MCFA_JREQ = 15040,
    MCFA_JREP = 15050,
    MCFA_CHSEL = 15060,
    MCFA_LREQ = 15070,
    MCFA_MOBINFO = 15080
};

/**
 * Class generated from <tt>ClusterMCFA/ClusterMCFAPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet ClusterMCFAPkt extends ClusterPkt {
 * 	int msgtype enum(MCFAMessageTypes);
 * 	int headId;
 * 	int originId;
 * 	double ERM;
 * 	double Speed;
 * 	double Direction;
 * 	int Question;
 * };
 * </pre>
 */
class ClusterMCFAPkt : public ::ClusterPkt
{
  protected:
    int msgtype_var;
    int headId_var;
    int originId_var;
    double ERM_var;
    double Speed_var;
    double Direction_var;
    int Question_var;

  private:
    void copy(const ClusterMCFAPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ClusterMCFAPkt&);

  public:
    ClusterMCFAPkt(const char *name=NULL, int kind=0);
    ClusterMCFAPkt(const ClusterMCFAPkt& other);
    virtual ~ClusterMCFAPkt();
    ClusterMCFAPkt& operator=(const ClusterMCFAPkt& other);
    virtual ClusterMCFAPkt *dup() const {return new ClusterMCFAPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getMsgtype() const;
    virtual void setMsgtype(int msgtype);
    virtual int getHeadId() const;
    virtual void setHeadId(int headId);
    virtual int getOriginId() const;
    virtual void setOriginId(int originId);
    virtual double getERM() const;
    virtual void setERM(double ERM);
    virtual double getSpeed() const;
    virtual void setSpeed(double Speed);
    virtual double getDirection() const;
    virtual void setDirection(double Direction);
    virtual int getQuestion() const;
    virtual void setQuestion(int Question);
};

inline void doPacking(cCommBuffer *b, ClusterMCFAPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ClusterMCFAPkt& obj) {obj.parsimUnpack(b);}


#endif // _CLUSTERMCFAPKT_M_H_
