//
// Generated file, do not edit! Created by opp_msgc 4.2 from RealLowestID/RealLowestIDPkt.msg.
//

#ifndef _REALLOWESTIDPKT_M_H_
#define _REALLOWESTIDPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ClusterPkt_m.h"
// }}



/**
 * Enum generated from <tt>RealLowestID/RealLowestIDPkt.msg</tt> by opp_msgc.
 * <pre>
 * enum ClusterLowestIdMessageTypes 
 * { 
 *     	CLUSTER_INFO		= 15009;
 *     	CLUSTER_INIT 		= 15010;
 *     	CLUSTER_JOIN 		= 15020;
 *     	CLUSTER_ACCEPTED 	= 15030;
 *     	CLUSTER_NEIGH_INQ 	= 15040;
 *     	CLUSTER_NEIGH_RESP 	= 15050;
 *     	CLUSTER_REJOIN		= 15060;
 * };
 * </pre>
 */
enum ClusterLowestIdMessageTypes {
    CLUSTER_INFO = 15009,
    CLUSTER_INIT = 15010,
    CLUSTER_JOIN = 15020,
    CLUSTER_ACCEPTED = 15030,
    CLUSTER_NEIGH_INQ = 15040,
    CLUSTER_NEIGH_RESP = 15050,
    CLUSTER_REJOIN = 15060
};

/**
 * Class generated from <tt>RealLowestID/RealLowestIDPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet RealLowestIDPkt extends ClusterPkt {
 * 	int msgtype enum(ClusterLowestIdMessageTypes);
 * 	int headId;
 * 	int originId;
 * 	string listingNodes;
 * 	
 * };
 * </pre>
 */
class RealLowestIDPkt : public ::ClusterPkt
{
  protected:
    int msgtype_var;
    int headId_var;
    int originId_var;
    opp_string listingNodes_var;

  private:
    void copy(const RealLowestIDPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RealLowestIDPkt&);

  public:
    RealLowestIDPkt(const char *name=NULL, int kind=0);
    RealLowestIDPkt(const RealLowestIDPkt& other);
    virtual ~RealLowestIDPkt();
    RealLowestIDPkt& operator=(const RealLowestIDPkt& other);
    virtual RealLowestIDPkt *dup() const {return new RealLowestIDPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getMsgtype() const;
    virtual void setMsgtype(int msgtype);
    virtual int getHeadId() const;
    virtual void setHeadId(int headId);
    virtual int getOriginId() const;
    virtual void setOriginId(int originId);
    virtual const char * getListingNodes() const;
    virtual void setListingNodes(const char * listingNodes);
};

inline void doPacking(cCommBuffer *b, RealLowestIDPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RealLowestIDPkt& obj) {obj.parsimUnpack(b);}


#endif // _REALLOWESTIDPKT_M_H_
